config/routes.rb
RubyTodo::Application.routes.draw do
  resources :to_dos

  root :to => 'to_dos#index'

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
  attr_accessible :status, :todo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  # GET /to_dos
  # GET /to_dos.json
  def index
    @to_dos = ToDo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @to_dos }
    end
  end

  # GET /to_dos/1
  # GET /to_dos/1.json
  def show
    @to_do = ToDo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @to_do }
    end
  end

  # GET /to_dos/new
  # GET /to_dos/new.json
  def new
    @to_do = ToDo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @to_do }
    end
  end

  # GET /to_dos/1/edit
  def edit
    @to_do = ToDo.find(params[:id])
  end

  # POST /to_dos
  # POST /to_dos.json
  def create
    @to_do = ToDo.new(params[:to_do])

    respond_to do |format|
      if @to_do.save
        format.html { redirect_to @to_do, notice: 'To do was successfully created.' }
        format.json { render json: @to_do, status: :created, location: @to_do }
      else
        format.html { render action: "new" }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /to_dos/1
  # PUT /to_dos/1.json
  def update
    @to_do = ToDo.find(params[:id])

    respond_to do |format|
      if @to_do.update_attributes(params[:to_do])
        format.html { redirect_to @to_do, notice: 'To do was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_dos/1
  # DELETE /to_dos/1.json
  def destroy
    @to_do = ToDo.find(params[:id])
    @to_do.destroy

    respond_to do |format|
      format.html { redirect_to to_dos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyTodo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/to_dos/_form.html.erb
<%= form_for(@to_do) do |f| %>
  <% if @to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
      <% @to_do.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :todo %><br />
    <%= f.text_field :todo %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/to_dos/edit.html.erb
<h1>Editing to_do</h1>

<%= render 'form' %>

<%= link_to 'Show', @to_do %> |
<%= link_to 'Back', to_dos_path %>

app/views/to_dos/index.html.erb
<h1>Listing to_dos</h1>

<table>
  <tr>
    <th>Todo</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @to_dos.each do |to_do| %>
  <tr>
    <td><%= to_do.todo %></td>
    <td><%= to_do.status %></td>
    <td><%= link_to 'Show', to_do %></td>
    <td><%= link_to 'Edit', edit_to_do_path(to_do) %></td>
    <td><%= link_to 'Destroy', to_do, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New To do', new_to_do_path %>

app/views/to_dos/new.html.erb
<h1>New to_do</h1>

<%= render 'form' %>

<%= link_to 'Back', to_dos_path %>

app/views/to_dos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Todo:</b>
  <%= @to_do.todo %>
</p>

<p>
  <b>Status:</b>
  <%= @to_do.status %>
</p>


<%= link_to 'Edit', edit_to_do_path(@to_do) %> |
<%= link_to 'Back', to_dos_path %>